version: "2.4"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123123"
      MYSQL_DATABASE: PRODUCT
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - product_network
  #    cpus: 1.5     # 최대 Docker CPU 할당 내에서 사용
  #    mem_limit: 768m # 최대 Docker Memory 할당 내에서 사용

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8089:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - product_network

  product-api-1:
    build:
      context: .
    container_name: product-api-1
    ports:
      - "8081:8080"
    environment:
      - INSTANCE_NAME=API-1
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/PRODUCT
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123123
    networks:
      - product_network
    depends_on:
      mysql:
        condition: service_healthy


  product-api-2:
      build:
        context: .
      container_name: product-api-2
      ports:
        - "8082:8080"
      environment:
        - INSTANCE_NAME=API-2
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/PRODUCT
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=123123
      networks:
        - product_network
      depends_on:
        mysql:
          condition: service_healthy

  product-api-3:
      build:
        context: .
      container_name: product-api-3
      ports:
        - "8083:8080"
      environment:
        - INSTANCE_NAME=API-3
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/PRODUCT
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=123123
      networks:
        - product_network
      depends_on:
        mysql:
          condition: service_healthy
  #
  #  nginx:
  #    build:
  #      context: ./nginx
  #    container_name: nginx
  #    ports:
  #      - "80:80"
  #    depends_on:
  #      - product-api-1
  #      - product-api-2
  #      - product-api-3
  #    networks:
  #      - product_network
  #    cpus: 0.5          # CPU 0.5개 제한
  #    mem_limit: 256m  # 메모리 256MB 제한

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - product_network
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - product_network

  #  nginx-exporter:
  #    image: nginx/nginx-prometheus-exporter:latest
  #    container_name: nginx-exporter
  #    command:
  #      - '--nginx.scrape-uri=http://nginx/stub_status'
  #    ports:
  #      - "9113:9113"
  #    depends_on:
  #      - nginx
  #    networks:
  #      - product_network

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - product_network

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    depends_on:
      - redis
    networks:
      - product_network

  zookeeper:
    image: zookeeper:3.7
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./jmx-kafka.yml:/etc/jmx-kafka.yml
    command:
      - /opt/bitnami/scripts/kafka/run.sh
      - --jmx-port=9999
    depends_on:
      - zookeeper

  kafka-exporter:
    image: prom/jmx-exporter
    ports:
      - "5556:5556"
    volumes:
      - ./jmx-kafka.yml:/etc/jmx-kafka.yml
    command:
      - java
      - -javaagent:/jmx_prometheus_javaagent-0.18.0.jar=5556:/etc/jmx-kafka.yml
      - -jar
      - kafka.jar


networks:
  product_network:
    driver: bridge
